- hosts: test-linux-1
  become: yes
  tasks:
    - include_role:
        name: azure-linux-configure-disk
    - include_role:
        name: azure-nginx

- hosts: test-linux-1
  tasks:
    - include_role:
        name: azure-f5
