- hosts: localhost
  tasks:
    - include_role:
        name: azure-provision-vm-windows
      when: os_type == 'Windows'
    - include_role:
        name: azure-provision-vm-linux
      when: os_type == 'Linux'
