- name: Set the right Monitoring Agent Options for Linux
  set_facts:
    virtual_machine_extension_type: OmsAgentForLinux
    type_handler_version: 1.7
  when: os_type == 'Linux'

- name: Set the right Monitoring Agent Options for Windows
  set_facts:
    virtual_machine_extension_type: MicrosoftMonitoringAgent
    type_handler_version: 1.0
  when: os_type == 'Windows'

- name: Enable Monitoring agent
  tags:
    - "monitoring-agent"
  azure_rm_virtualmachine_extension:
    name: OMSExtension
    resource_group: "{{ resource_group }}"
    virtual_machine_name: "{{ vm_name }}"
    publisher: Microsoft.EnterpriseCloud.Monitoring
    virtual_machine_extension_type: "{{ virtual_machine_extension_type }}"
    type_handler_version: "{{ type_handler_version }}"
    settings: '{"workspaceId": "{{ log_analytics_workspace_id }}"}'
    protected_settings: '{"workspaceKey": "{{ log_analytics_workspace_key }}"}'
